name: main

on:
  push:
    branches: [ main ]
    paths:
      - Sources/**
      - Tests/**
      - Package.swift
      - .github/**
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - Sources/**
      - Tests/**
      - Package.swift
      - .github/**

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and test
        run:  swift test
